---

jobs:
- name: job-0
  plan:
  - get: counter
    params: {inc: yes}
  - put: counter
    params: {file: counter/count}

- name: job-1
  plan:
  - get: counter
    passed: [job-0]

resources:
- name: counter
  type: counter-resource
  source:
    aws_access_key_id:      {fill_in}
    aws_secret_access_key:  {fill_in}
    region:                 {fill_in}
    bucket:                 {fill_in}
    key:                    {fill_in}

resource_types:
- name: counter-resource
  type: docker-image
  source:
    repository: jinlee/counter-resource

...
